baseurl:
url: https://JiachengWu-5.github.io
title: Jiacheng Wu
subtitle: "This is Jiacheng Wu's website."
description: "Jiacheng Wu's personal page"
date_format: "ordinal"
# timezone: Asia/Hong Kong
encoding: "utf-8"
side_bar_repo_limit: 5

author: Jiacheng Wu
organization: HKUST
organization_url: https://hkust.edu.hk/
github_username: JiachengWu-5
location: Hong Kong, China
email: jwudm@connect.ust.hk

# Navigation
navs:


  -
    href: /
    label: Homepage
  -
    href: /cv/
    label: CV
    
    
  -
    href: /project/
    label: Project

  -
    href: /blog/
    label: Blog

#  -
#    href: /wiki/
#    label: Wiki

  # -
  #   href: /links/
  #   label: Links

# RSS
subscribe_rss: /feed.xml

# Jekyll
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: https://jiachengwu-5.github.io/

# Build settings
pagination:
  enabled: true
  per_page: 5
  permalink: 'page:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
# Search
simple_jekyll_search:
    fulltext: true # full text search enable
    limit: 10 # limitation of the search results to show

# Analytics
google:
    analytics_id: UA-80669434-1
github: [metadata]
